# Generated by Django 5.1.2 on 2024-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
