# Generated by Django 5.1.2 on 2024-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_alter_facture_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
